# Comprehensive, layman-friendly Senate of Pakistan workflow catalogue.
# Process descriptions are educational models based on the Constitution,
# Senate Rules, and official Senate explanatory material. Always verify exact
# current legal requirements against the latest official texts.

WORKFLOWS = {
"00 — MASTER: How Senate Business Fits Together": {
"category":"MASTER MAP","summary":"The big picture: people become Senators; leadership organizes the House; the Secretariat schedules business; business is debated in the House and/or committees; decisions are recorded; some matters move to the National Assembly, a joint sitting or the President.","steps":[
("START","Senate exists as a continuing House","Membership continues through the constitutional cycle; individual members change over time.","start"),
("1","Members / Senators","Senators enter through the constitutional election process and then complete oath and membership formalities.","people"),
("2","Leadership","Senators elect the Chairman and Deputy Chairman as provided by the Constitution.","people"),
("3","Session / Sitting","A session is summoned; individual sittings conduct the House's business.","schedule"),
("4","Orders of the Day","The Secretary prepares the day's schedule. Business is normally taken in the order listed unless the Chair directs otherwise.","schedule"),
("5","Types of Business","Bills, questions, calling-attention notices, motions, resolutions, points of order, committee business and other parliamentary business can come before the House.","business"),
("6","Committee Examination","Bills and referred matters may go to Standing, Functional, Special, Select or other committees according to the applicable rules.","committee"),
("7","House Deliberation","Members speak, ask questions, move amendments or motions, and the Chair applies the rules of procedure.","house"),
("8","Decision / Outcome","The applicable business may be passed, rejected, adopted, noted, referred, answered, reported or otherwise disposed of.","decision"),
("9","Next Constitutional Stage","Depending on the matter, it may go to the National Assembly, a joint sitting, the President, or remain within Senate/committee processes.","external"),
("END","Official Record","Hansard/debates, journals, reports, Acts and other parliamentary records document the work and outcome.","record"),
]},
"01 — SENATOR: Selection → Oath → Seat": {"category":"MEMBERSHIP","summary":"How a person moves from an available Senate seat through nomination/election and formal membership.","steps":[
("START","Seat / vacancy exists","A seat becomes available through the constitutional cycle or a casual-vacancy process.","start"),
("1","Relevant electoral college","The applicable electoral college participates under the Constitution and election law.","people"),
("2","Nomination & scrutiny","Candidates are nominated and scrutinized under the applicable election framework.","process"),
("3","Senate election","The relevant electoral college votes using the legally prescribed method.","decision"),
("4","Result / notification","The competent election authority declares and notifies the result.","record"),
("5","Oath & formalities","The elected Senator completes the constitutional oath and required membership formalities.","process"),
("END","Senator takes seat","The member participates in Senate business subject to the Constitution and Rules.","end"),
]},
"02 — CHAIRMAN: Election Workflow": {"category":"LEADERSHIP","summary":"How the Senate chooses its Chairman from among Senators.","steps":[
("START","Relevant constitutional stage","Following the relevant Senate reconstitution/election stage, the House proceeds to elect its Chairman.","start"),
("1","Senate sitting convened","The House meets under the applicable constitutional and rules framework.","schedule"),
("2","Candidates from among Senators","Members may be proposed/nominated according to the applicable procedure.","people"),
("3","Election by Senators","The Senate elects the Chairman from among its members.","decision"),
("4","Declaration of result","The result is formally announced in the House.","record"),
("END","Chairman presides","The Chairman presides over Senate sittings and exercises powers assigned by the Constitution and Rules.","end"),
]},
"03 — DEPUTY CHAIRMAN: Election Workflow": {"category":"LEADERSHIP","summary":"How the Senate chooses its Deputy Chairman from among Senators.","steps":[
("START","Relevant constitutional stage","The Senate proceeds to elect the Deputy Chairman under the constitutional procedure.","start"),
("1","Candidates from among Senators","Nominations/proposals are handled under the applicable procedure.","people"),
("2","Election by Senators","The Senate elects the Deputy Chairman from among its members.","decision"),
("3","Result announced","The Chair/House records and announces the result.","record"),
("END","Deputy Chairman available to preside","The Deputy Chairman performs the constitutional/rules-based functions assigned to the office.","end"),
]},
"04 — SESSION & SITTING: Summoning → Orders of Day": {"category":"HOUSE BUSINESS","summary":"How a Senate sitting becomes an organized agenda of parliamentary business.","steps":[
("START","Need for Senate business","A constitutional/parliamentary session is required to transact business.","start"),
("1","Session summoned","The Senate is summoned under the constitutional framework.","external"),
("2","Sitting arranged","A particular meeting/sitting is scheduled.","schedule"),
("3","Notices received","Bills, questions, motions, resolutions, notices and committee matters enter the Secretariat process.","process"),
("4","Secretariat scrutiny & arrangement","The Secretariat processes notices and arranges admissible business under the Rules.","process"),
("5","Orders of the Day prepared","The Secretary prepares the day's business schedule.","schedule"),
("6","Sitting opens","The Chair calls the House to order and business begins according to the applicable agenda.","house"),
("7","Business transacted","Questions, legislation, motions, resolutions and other listed business are taken up.","business"),
("END","Proceedings recorded","The official parliamentary record captures what was transacted and decided.","record"),
]},
"05 — ORDINARY BILL: Idea → Act": {"category":"LEGISLATION","summary":"A practical visual model of the ordinary Bill route, including committee scrutiny and movement between the two Houses.","steps":[
("START","Policy idea / legislative proposal","A member or Government develops an idea that may require legislation.","start"),
("1","Draft Bill + objects/reasons","The proposal is put into legislative form and processed for introduction.","process"),
("2","Notice & introduction","The Bill is placed before the House under the applicable procedure.","house"),
("3","Standing Committee scrutiny","A Bill is ordinarily referred to the relevant committee unless the Rules permit the requirement to be dispensed with.","committee"),
("4","Committee examination","Members examine the Bill, hear relevant views where appropriate, and consider amendments.","committee"),
("5","Committee report","The committee reports its findings/recommendations back to the House.","record"),
("6","House consideration","The Bill is taken up through the applicable reading/consideration stages.","house"),
("7","Clause-by-clause + amendments","Clauses are considered and amendments may be proposed and decided.","decision"),
("8","Third reading / passage","The House decides whether to pass the Bill in its final form.","decision"),
("9","Other House","If passed by one House, the Bill proceeds to the other House under the constitutional route.","external"),
("10","Same text?","If the other House passes it without amendment, it proceeds to the President. If amended, it returns to the originating House for the applicable next step.","decision"),
("END","Presidential stage → Act","After completion of the parliamentary route, the Bill goes through the constitutional assent process and may become an Act.","end"),
]},
"06 — MONEY BILL: National Assembly → Senate Recommendations": {"category":"LEGISLATION / FINANCE","summary":"The special constitutional route for a Money Bill: it originates in the National Assembly and the Senate has a recommendation role.","steps":[
("START","Money Bill prepared","A financial measure falling within the constitutional Money Bill framework is prepared.","start"),
("1","Introduced in National Assembly","A Money Bill originates in the National Assembly.","external"),
("2","Copy transmitted to Senate","The Senate receives a copy for recommendations under the Constitution.","house"),
("3","Senate examines / recommends","Senators may consider the Bill and formulate recommendations within the constitutional period.","decision"),
("4","Recommendations sent to National Assembly","The Senate's recommendations are transmitted to the National Assembly.","external"),
("5","National Assembly considers recommendations","The National Assembly considers the Senate's recommendations according to the constitutional process.","decision"),
("6","Presidential stage","After completion of the parliamentary route, the Bill proceeds to the President under the Constitution.","external"),
("END","Law / financial measure","The completed measure takes effect according to the Constitution and law.","end"),
]},
"07 — CONSTITUTIONAL AMENDMENT: Two-Thirds Route": {"category":"CONSTITUTION","summary":"A visual model of the special procedure for changing the Constitution.","steps":[
("START","Constitutional Amendment Bill","A proposal is drafted as a Bill to amend the Constitution.","start"),
("1","Introduced in first House","The Bill enters parliamentary consideration under the constitutional and Rules framework.","house"),
("2","First House: two-thirds total membership","The constitutional threshold must be met in the House considering the amendment.","decision"),
("3","Second House","The Bill is transmitted to the other House.","external"),
("4","Second House: two-thirds total membership","The constitutional threshold must be met in the second House as required.","decision"),
("5","Provincial-consent issue where applicable","Certain constitutional changes affecting specified provincial matters have additional constitutional requirements.","decision"),
("6","President","The completed parliamentary Bill proceeds to the constitutional presidential stage.","external"),
("END","Constitution amended","The constitutional amendment takes effect according to the Constitution.","end"),
]},
"08 — STANDING COMMITTEE: Referral → Report": {"category":"COMMITTEES","summary":"How committee work supports scrutiny of Bills and other matters.","steps":[
("START","Bill / matter referred","A Bill or other matter comes within a committee's remit through the applicable procedure.","start"),
("1","Committee agenda","The committee schedules the matter for consideration.","schedule"),
("2","Briefings / evidence / documents","The committee may call officials, obtain information and examine relevant material.","committee"),
("3","Detailed scrutiny","Members examine clauses, policy, administration, delegated legislation or the referred issue as applicable.","committee"),
("4","Amendments / recommendations","The committee may formulate amendments, observations or recommendations within its authority.","decision"),
("5","Committee report","The committee adopts/presents its report through the prescribed procedure.","record"),
("6","Report before House / follow-up","The House may consider the report, and the committee may continue oversight/follow-up as authorized.","house"),
("END","Oversight / legislative input","Committee work feeds into parliamentary scrutiny and accountability.","end"),
]},
"09 — QUESTIONS: Notice → Minister's Answer → Supplementary": {"category":"ACCOUNTABILITY","summary":"How a Senator uses questions to seek information and draw attention to public concerns.","steps":[
("START","Member identifies issue","A Senator identifies a matter of public concern within the relevant Minister's cognizance.","start"),
("1","Question drafted","The question is prepared within the applicable rules.","process"),
("2","Notice to Secretariat","Written notice is submitted through the prescribed process; ordinary questions generally require advance notice.","process"),
("3","Admissibility / listing","The Secretariat processes the question and it is listed when admissible.","schedule"),
("4","Question Hour / answer","The question is asked and the Minister/Government provides an answer.","house"),
("5","Supplementary questions","Members may seek clarification through supplementary questions under the Rules.","business"),
("6","Follow-up / record","The exchange becomes part of the parliamentary record and may inform later scrutiny.","record"),
("END","Accountability information obtained","The purpose is information, explanation and attention to public concerns.","end"),
]},
"10 — CALLING ATTENTION NOTICE: Urgent Public Importance": {"category":"ACCOUNTABILITY","summary":"How the House can bring an urgent public-interest matter to a Minister's attention.","steps":[
("START","Urgent public matter","A Senator identifies a matter of urgent public importance.","start"),
("1","Notice submitted","The member gives notice under the applicable Rules.","process"),
("2","Admissibility / scheduling","The notice is processed and, when admissible, entered in the Orders of the Day.","schedule"),
("3","Matter called in House","The Chair takes up the listed Calling Attention Notice.","house"),
("4","Minister makes brief statement","The concerned Minister responds to the matter.","business"),
("5","Clarification / discussion as permitted","The House deals with the matter according to the applicable rule and time available.","decision"),
("END","Official record","The issue and Government response are recorded.","record"),
]},
"11 — RESOLUTION: Notice → Debate → Decision": {"category":"RESOLUTIONS","summary":"A general model for a Senate resolution, including constitutional/statutory resolutions where a different rule applies.","steps":[
("START","Issue of public interest","A member or Minister wants the Senate to express an opinion, recommendation or take a resolution-based action.","start"),
("1","Resolution drafted","The proposed resolution is prepared in the required form.","process"),
("2","Notice submitted","Notice is given under the applicable period and procedure.","process"),
("3","Admissibility / priority","The Chair/Secretariat processes admissibility and priority according to the Rules.","schedule"),
("4","Listed in Orders of the Day","The resolution is scheduled for House business.","schedule"),
("5","Mover introduces / explains","The mover presents the resolution.","house"),
("6","Debate","Members discuss the issue and may propose changes where the rules permit.","business"),
("7","Decision / vote where applicable","The House deals with the resolution under the applicable procedure.","decision"),
("END","Resolution adopted / disposed of","The outcome is entered into the parliamentary record and may communicate the Senate's position.","end"),
]},
"12 — MOTION: Notice → Debate → Outcome": {"category":"MOTIONS","summary":"Motions cover several parliamentary purposes. This workflow shows the common path from notice to House consideration and outcome.","steps":[
("START","Matter requiring House consideration","A member/Minister seeks to raise a policy, situation, statement or other matter through a motion.","start"),
("1","Motion drafted","The motion is prepared under the relevant rule/type.","process"),
("2","Notice / admissibility","The notice is processed under the applicable Rules.","process"),
("3","Listed / taken up","The motion appears in the relevant business schedule.","schedule"),
("4","Mover speaks","The mover explains the matter.","house"),
("5","Debate","Members debate according to the particular motion procedure.","business"),
("6","Vote?","Some motions are debated without a final vote unless a substantive motion is moved; other motions are decided by the House.","decision"),
("END","Outcome recorded","The parliamentary record shows what was debated and what decision, if any, was taken.","record"),
]},
"13 — PRIVILEGE: Question of Privilege": {"category":"MOTIONS / PRIVILEGE","summary":"A simplified route for raising a matter involving an alleged breach of parliamentary privilege.","steps":[
("START","Possible breach of privilege","A member identifies a matter involving the privilege of a member, the Senate or a committee.","start"),
("1","Question raised","The member raises the matter according to the applicable Rules.","house"),
("2","Chair decides procedural course","The Chair applies the Rules and may determine whether the matter proceeds further.","decision"),
("3","Committee / inquiry where referred","Where applicable, the matter may be referred to the Committee on Rules of Procedure and Privileges or another competent forum.","committee"),
("4","Examination / report","The committee examines the matter and reports as prescribed.","committee"),
("END","House / Chair outcome","The matter is disposed of according to the applicable constitutional and rules-based procedure.","end"),
]},
"14 — PETITION: Public Petition → Senate Process": {"category":"PUBLIC PARTICIPATION","summary":"A visual model of how a public petition can enter Senate business, subject to admissibility and the Rules.","steps":[
("START","Public grievance / issue","A person or group seeks parliamentary attention to a matter within the permissible scope.","start"),
("1","Petition prepared","The petition is prepared in the required form and on an eligible subject.","process"),
("2","Submission / scrutiny","The Secretariat checks the petition under the applicable rules.","process"),
("3","Admitted / presented","If admissible, it enters the parliamentary process.","schedule"),
("4","Committee / House consideration","The matter may be considered through the competent committee or House process.","committee"),
("5","Observations / recommendations","The competent parliamentary forum considers the issue and may make observations or recommendations.","decision"),
("END","Outcome / record","The petition and its parliamentary handling are recorded under the applicable procedure.","record"),
]},
"15 — JOINT SITTING: Two Houses → Joint Decision": {"category":"INTER-HOUSE","summary":"A joint sitting brings the National Assembly and Senate together when the Constitution provides for that route.","steps":[
("START","Constitutional trigger","A matter qualifies for joint-sitting consideration under the Constitution/law.","start"),
("1","Joint sitting convened","The two Houses assemble together under the applicable constitutional procedure.","external"),
("2","Business placed before joint sitting","The specified matter is presented for consideration.","schedule"),
("3","Debate by members","Members of both Houses participate under the joint-sitting rules.","house"),
("4","Decision / vote","The joint sitting decides the matter according to the constitutional threshold applicable to it.","decision"),
("END","Constitutional outcome","The decision has the legal effect provided by the Constitution for that joint-sitting matter.","end"),
]},
"16 — PRESIDENTIAL ASSENT: Parliament → President → Law": {"category":"CONSTITUTIONAL / LEGISLATIVE","summary":"The final constitutional stage for Bills that have completed the required parliamentary route.","steps":[
("START","Bill completes parliamentary route","The Bill has reached the stage at which presidential action is required under the Constitution.","start"),
("1","Bill presented to President","The completed Bill is sent to the President.","external"),
("2","Constitutional presidential action","The President acts according to the constitutional assent mechanism applicable to the Bill.","decision"),
("3","If returned / reconsideration route applies","Where the Constitution permits return/reconsideration, Parliament deals with the Bill under that route.","decision"),
("END","Assent / law takes effect","After completion of the constitutional process, the Bill becomes law as provided by the Constitution.","end"),
]},

"18 — COMMITTEE OVERSIGHT: Ministry → Evidence → Recommendations": {"category":"COMMITTEES / OVERSIGHT","summary":"A committee can examine administration, policies, delegated legislation, budgetary utilization and other matters within its remit.","steps":[
("START","Ministry / public-body issue","A policy, administration, spending or implementation issue falls within a committee's remit.","start"),
("1","Matter placed before committee","The committee schedules the issue or receives it by referral.","schedule"),
("2","Documents requested","The committee obtains papers, explanations and relevant information.","process"),
("3","Officials / stakeholders heard","The committee may call for views, briefings or evidence as permitted.","committee"),
("4","Questions & scrutiny","Members examine performance, policy, implementation or delegated legislation.","house"),
("5","Findings / recommendations","The committee develops observations and recommendations.","decision"),
("6","Report / follow-up","The report is presented and follow-up may be undertaken.","record"),
("END","Executive accountability","The process supports parliamentary oversight of government administration within the committee's mandate.","end"),
]},
"19 — PRIVATE MEMBER'S BILL: Member → House": {"category":"LEGISLATION","summary":"A private member can introduce a Bill, subject to notice, drafting, scrutiny, scheduling and the applicable legislative process.","steps":[
("START","Member has legislative idea","A Senator develops a proposal requiring legislation.","start"),
("1","Draft Bill + statement","The Bill and required supporting material are prepared.","process"),
("2","Advance written notice","The member gives notice under the applicable Rules.","process"),
("3","Secretariat scrutiny","The proposal is checked for constitutional/rules requirements and drafting support may be provided.","process"),
("4","Listed for introduction","The Bill is placed in the appropriate Private Members' Business schedule.","schedule"),
("5","Introduction","The member introduces the Bill.","house"),
("6","Committee + consideration","The Bill follows the applicable committee and House stages.","committee"),
("END","Passed / rejected / otherwise disposed of","The House and, where applicable, the other House determine the Bill's outcome.","end"),
]},
"20 — GOVERNMENT BILL: Ministry → Minister → Parliament": {"category":"LEGISLATION","summary":"How a Government legislative proposal is brought into Senate business when the Senate is the originating House or receives the Bill from the National Assembly.","steps":[
("START","Government policy proposal","A ministry/Government develops legislation.","start"),
("1","Bill drafted","The Bill and statement of objects/reasons are prepared.","process"),
("2","Minister gives notice / sponsors Bill","The Government member initiates the parliamentary process under the Rules.","people"),
("3","Orders of the Day","The Bill is scheduled for Government Business.","schedule"),
("4","Introduction / first stage","The Bill is introduced and enters the applicable legislative process.","house"),
("5","Committee scrutiny","The relevant committee examines the Bill as required.","committee"),
("6","House consideration & vote","The Senate considers, debates, amends where applicable and decides.","decision"),
("7","Other House / President","The Bill follows the applicable two-House and presidential route.","external"),
("END","Act or further parliamentary action","The final outcome is recorded and implemented according to law.","end"),
]},
"21 — POINT OF ORDER: Procedural Issue During Sitting": {"category":"HOUSE PROCEDURE","summary":"A simplified view of how a member can raise a procedural point during a sitting.","steps":[
("START","Procedural issue arises","A member believes a matter of procedure requires the Chair's attention.","start"),
("1","Member raises Point of Order","The member addresses the Chair under the applicable Rules.","house"),
("2","Chair hears the point","The Chair considers the procedural issue.","decision"),
("3","Ruling / direction","The Chair may rule, give a direction or indicate the applicable procedure.","decision"),
("END","House proceeds","The sitting continues according to the Chair's ruling and Rules.","end"),
]},
"22 — ORDINANCE: Senate Disapproval / Extension Role": {"category":"CONSTITUTIONAL BUSINESS","summary":"The Senate may have constitutional business concerning an Ordinance, including disapproval or a permitted extension process.","steps":[
("START","Presidential Ordinance exists","An Ordinance is promulgated under the constitutional conditions.","start"),
("1","Ordinance laid before Parliament","The constitutional laying procedure applies.","external"),
("2","Senate considers","The Senate may consider the Ordinance under the Constitution and Rules.","house"),
("3","Possible resolution","The Senate may use the constitutional resolution mechanism where applicable.","decision"),
("4","Disapprove / extension route / expiry","The Ordinance proceeds according to the constitutional outcome and time limits.","decision"),
("END","Constitutional outcome recorded","The result is reflected in the parliamentary record and legal status of the Ordinance.","end"),
]},
"23 — PAPERS / REPORTS LAID BEFORE SENATE": {"category":"DOCUMENTS & RECORDS","summary":"How reports, statements and other papers can become House business and be available for discussion or record.","steps":[
("START","Report / paper prepared","A constitutional, statutory, Government or parliamentary report becomes due.","start"),
("1","Paper transmitted to Secretariat","The document is received through the prescribed channel.","process"),
("2","Scrutiny / listing","The Secretariat processes and schedules the paper where required.","schedule"),
("3","Laid on Table / before House","The document is formally laid before the Senate according to the applicable procedure.","house"),
("4","Discussion / reference where permitted","Some reports may be discussed, referred or acted upon according to the Constitution and Rules.","business"),
("END","Official parliamentary record","The paper and its handling become part of the official record.","record"),
]},
"24 — CHAIR'S RULING: Issue → Interpretation → Ruling": {"category":"CHAIR / PROCEDURE","summary":"How procedural or constitutional questions raised in the House can result in a ruling of the Chair.","steps":[
("START","Procedural / constitutional question","An issue arises during Senate proceedings.","start"),
("1","Question raised / referred","The issue is placed before the Chair under the applicable procedure.","house"),
("2","Relevant Constitution / Rules considered","The Chair and Secretariat consider the applicable provisions and parliamentary precedent.","process"),
("3","Chair gives ruling","The Chair decides the procedural question.","decision"),
("4","Ruling recorded / published","Rulings may be compiled and made available as parliamentary precedents.","record"),
("END","Proceedings continue","The House proceeds in accordance with the ruling and applicable Rules.","end"),
]},
}

DOMAIN = {
"01 Membership": ["Senator selection", "Oath and membership", "Casual vacancies", "Roll of Members"],
"02 Leadership": ["Chairman", "Deputy Chairman", "Leader of House", "Leader of Opposition", "Chair's rulings"],
"03 House & Sessions": ["Sessions", "Sittings", "Orders of the Day", "Quorum", "Debate", "Voting", "Points of Order"],
"04 Legislative Business": ["Government Bills", "Private Members' Bills", "Ordinary Bills", "Money Bills", "Constitutional Amendments", "Amendments", "Presidential Assent"],
"05 Committee Business": ["Standing Committees", "Functional Committees", "Special Committees", "Select Committees on Bills", "Committee of the Whole", "Committee reports", "Oversight"],
"06 Accountability": ["Questions", "Supplementary Questions", "Calling Attention Notices", "Government responses", "Committee oversight"],
"07 Motions & Resolutions": ["Motions", "Adjournment Motions", "Privilege", "Resolutions", "Motion of Thanks", "Constitutional resolutions"],
"08 Public Participation": ["Public Petitions", "Public-interest matters", "Parliamentary forums"],
"09 Inter-House / Constitutional": ["National Assembly interaction", "Joint Sittings", "President", "Ordinances", "Constitutional procedures"],
"10 Records & Secretariat": ["Hansard / Debates", "Daily Journals", "Synopsis Journals", "Bills Register", "Reports", "Orders of the Day", "Publications"],
}

SOURCES = [
("Senate Orders of the Day", "https://senate.gov.pk/en/order_of_day.php"),
("Senate FAQ / Parliamentary Procedure", "https://senate.gov.pk/en/faq.php"),
("Senate Committees", "https://senate.gov.pk/en/all_committees.php"),
("Senate Rules of Procedure and Conduct of Business", "https://www.senate.gov.pk/uploads/documents/updatedrpcb.pdf"),
("Senate Handbook for Members", "https://www.senate.gov.pk/uploads/documents/Handbook_for_Members_Final-Ismail.pdf"),
("Senate Manual", "https://www.senate.gov.pk/uploads/documents/Senate-Manual.pdf"),
]
